# Generated by Django 5.0.6 on 2024-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discounted_price_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MN', 'Men'), ('WM', 'Women'), ('KD', 'Kid')], max_length=2),
        ),
    ]
