# Generated by Django 5.0.6 on 2024-06-24 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_discription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('Province', models.CharField(choices=[('MP', 'Mpumalanga'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu Natal'), ('FS', 'Free State'), ('WC', 'Western Cape'), ('NW', 'North West'), ('GP', 'Northen Cape'), ('LP', 'Limpopo'), ('EC', 'Eastern Cape')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
