# Generated by Django 5.0.6 on 2024-06-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Province',
            new_name='province',
        ),
    ]
