# Generated by Django 5.0.6 on 2024-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_province_customer_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(choices=[('Mpumalanga', 'Mpumalanga'), ('Gauteng', 'Gauteng'), ('KwaZulu Natal', 'KwaZulu Natal'), ('Free State', 'Free State'), ('Western Cape', 'Western Cape'), ('North West', 'North West'), ('Northen Cape', 'Northen Cape'), ('Limpopo', 'Limpopo'), ('Eastern Cape', 'Eastern Cape')], max_length=100),
        ),
    ]
