# Generated by Django 5.0.6 on 2024-06-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_razorpay_order_id_payment_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='8f8ba9a3aef7', max_length=100, unique=True),
        ),
    ]
